### ISSUE TITLE
Please consider uploading the PCB schematics

### ISSUE THREAD

**Issue by manutenfruits** [hanneslinder/esp-pixel-matrix#1]
Hi, I got your pcb fabricated but I'm missing some information like schematics, and what component goes in the small square (I'm guessing a photoresistor?).

I know I can reverse engineer it but would be great if we had access to the original schematic, or even better, the whole kicad project (if you used that!).

Thanks!

**Comment by hanneslinder** [comment]
Sorry for the late reply, completely missed your comment. 
Regarding the schematic, I created it with [EasyEDA](https://easyeda.com/), so there is no kicad file I can share. 

Now that you point it out I never specified what the additional through holes are for 🙈 
The larger one is for providing power and the smaller one is for a push button that resets the clock when pressed for 5 seconds. 

I've attached a picture of the backside of the clock, hope that clears it up a bit
![20220120_125402](https://github.com/hanneslinder/esp-pixel-matrix/assets/3353071/a3394253-fa9c-44ac-9f9e-33a2050db4e4)

Let me know if you have any more questions.
Cheers!
