### ISSUE TITLE
Informations ?

### ISSUE THREAD

**Issue by spordiab** [hanneslinder/esp-pixel-matrix#2]
Thank you for your project, however I don't have much programming knowledge, I use Arduino IDE and I have the same ESP32 board with the same Matrix screen.  I wanted to know if you could generate a.bin file to flash directly with ESPHome Flasher, it would be easier for beginners.  Thank you so much

**Comment by hanneslinder** [comment]
Thanks for the suggestion and sorry for my late reply.  
A `.bin` file sounds like an interesting addition to help getting started with the project faster. I'll look into it and add it to the project as soon as I find the time 👍

**Comment by hanneslinder** [comment]
@spordiab I've added pre-build files for the `esp32doit-devkit-v1` board in the `/bin` directory. Please note that you need to flash both files!
Let me know if this works for you. 

cheers!

**Comment by spordiab** [comment]
OMG, Thanks 😊
